# Generated by Django 4.2.1 on 2023-05-05 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('body', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
