# Generated by Django 4.2.1 on 2023-05-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0002_rename_date_created_features_datecreated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='title',
            new_name='MainTitle',
        ),
    ]
